### PR TITLE
[FLINK-34237][connectors/mongodb] Update MongoWriterITCase to be compatible with updated SinkV2 interfaces

### PR DESCRIPTION
**Pull request by Jiabao-Sun**
[FLINK-34237][connectors/mongodb] Update MongoWriterITCase to be compatible with updated SinkV2 interfaces

### CODE REVIEW

**Comment by Jiabao-Sun** [comment]
The modification to MongoWriterITCase is due to https://github.com/apache/flink/pull/24180#discussion_r1467184292.

@leonardBang please help take a look.

**Comment by WencongLiu** [comment]
Hi @Jiabao-Sun , I've opened another pull request to revert the breaking changes in flink repo. All connectors won't meet this issue after the PR is merged.

**Review by leonardBang — APPROVED** [review]
Thanks @Jiabao-Sun for the update, LGTM. Could you change the PR title as well?

**Comment by Jiabao-Sun** [comment]
Thanks @leonardBang for the review.
PR title was updated.

**Review by leonardBang — APPROVED** [review]

**Pull request merged**
