### PR TITLE
[FLINK-34216][connectors/mongodb] FLIP-377: Support fine-grained configuration to control filter push down for MongoDB Connector

### PR DESCRIPTION
**Pull request by Jiabao-Sun**
[FLINK-34216][connectors/mongodb] FLIP-377: Support fine-grained configuration to control filter push down for MongoDB Connector

This improvement implements [FLIP-377 Support fine-grained configuration to control filter push down for Table/SQL Sources](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=276105768)

This FLIP has 2 goals:

- Introduces a new configuration filter.handling.policy to the JDBC and MongoDB connector.
- Suggests a convention option name if other connectors are going to add an option for the same purpose.

### CODE REVIEW

**Comment by Jiabao-Sun** [comment]
Hi @eskabetxe, @RocMarshal, can you help take a look as well?

**Comment by eskabetxe** [comment]
hi @Jiabao-Sun 
I'm not an contributor to this connector but it LGTM

**Review by eskabetxe — APPROVED** [review]

**Review by RocMarshal — APPROVED** [review]
Thanks @Jiabao-Sun for the pr and @eskabetxe for the review.
+1.

**Comment by Jiabao-Sun** [comment]
Thanks @eskabetxe and @RocMarshal for the review.

**Pull request merged**
